# encoding: utf-8
"""This file includes necessary params, info."""
import mmcv
import os.path as osp

import numpy as np

# ---------------------------------------------------------------- #
# ROOT PATH INFO
# ---------------------------------------------------------------- #
cur_dir = osp.abspath(osp.dirname(__file__))
root_dir = osp.normpath(osp.join(cur_dir, ".."))
# directory storing experiment data (result, model checkpoints, etc).
output_dir = osp.join(root_dir, "output")

data_root = osp.join(root_dir, "datasets")
bop_root = osp.join(data_root, "BOP_DATASETS/")

# ---------------------------------------------------------------- #
# HB DATASET
# ---------------------------------------------------------------- #
dataset_root = osp.join(data_root, "cap_bottle")
train_dir = osp.join(dataset_root, "train_5k")
test_dir = osp.join(dataset_root, "test_100")
model_dir = osp.join(dataset_root, "models")
vertex_scale = 1.0#0.001
model_eval_dir = osp.join(dataset_root, "models")

# object info
id2obj = {
    1: "01_cap",
    2: "02_bottle"
}
objects = [str(obj) for obj in id2obj.values()]
obj_num = len(id2obj)
obj2id = {_name: _id for _id, _name in id2obj.items()}

model_paths = [osp.join(model_dir, "obj_{:06d}.ply").format(_id) for _id in id2obj]
texture_paths = None
model_colors = [((i + 1) * 5, (i + 1) * 5, (i + 1) * 5) for i in range(obj_num)]  # for renderer

# yapf: disable
diameters = np.array([
    232.572, 257.407, 166.500, 179.029, 205.401,
    121.408, 263.718, 186.813, 166.572, 180.804,
    238.514, 156.887, 145.339, 243.733, 113.032,
    101.588, 132.771, 211.134, 185.582, 244.828,
    212.603, 190.203, 233.857, 252.263, 202.905,
    183.794, 264.442, 477.464, 198.004, 416.202,
    157.985, 201.759, 187.233
]) / 1000.0
# yapf: enable

# Camera info
width = 640
height = 480
zNear = 0.25
zFar = 6.0
center = (height / 2, width / 2)
camera_matrix = np.array([[537.4799, 0.0, 318.8965], [0.0, 536.1447, 238.3781], [0.0, 0.0, 1.0]])
camera_matrix = np.array([[440.9264039920957, 0, 320.0], [0, 440.9263911506707, 240.0], [0, 0, 1]])

depth_factor = 1000.0


def get_models_info():
    """key is str(obj_id)"""
    models_info_path = osp.join(model_dir, "models_info.json")
    assert osp.exists(models_info_path), models_info_path
    models_info = mmcv.load(models_info_path)  # key is str(obj_id)
    return models_info


def get_fps_points():
    """key is str(obj_id) generated by
    core/gdrn_modeling/tools/hb/hb_1_compute_fps.py."""
    fps_points_path = osp.join(model_dir, "fps_points.pkl")
    assert osp.exists(fps_points_path), fps_points_path
    fps_dict = mmcv.load(fps_points_path)
    return fps_dict


def get_keypoints_3d():
    """key is str(obj_id) generated by
    core/roi_pvnet/tools/hb/hb_1_compute_keypoints_3d.py."""
    keypoints_3d_path = osp.join(model_dir, "keypoints_3d.pkl")
    assert osp.exists(keypoints_3d_path), keypoints_3d_path
    kpts_dict = mmcv.load(keypoints_3d_path)
    return kpts_dict
